### ISSUE TITLE
您好 这个插件的用途是什么 看文档没太明白

### ISSUE THREAD

**Issue by YuyangHYY** [lmk123/oh-my-wechat#1]

**Comment by lmk123** [comment]
我平常喜欢用针对 MacOS 中的微信的[这款插件](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS)拦截别人撤回的消息，但是一旦微信自动更新了，这个插件就需要重新安装，我就又得按照文档上的步骤执行一遍命令，而且直到别人撤回了一条消息之后我才知道微信自动更新导致插件失效了。

所以我写了这个脚本，通过命令行的方式自动下载、安装防撤回插件，并打开微信。其实我想要的使用方式是在用鼠标点击微信前自动运行脚本，但是我还没找到这样做的方法，所以就转而做成了一个打开微信的脚本，并在打开前自动检测插件是否安装过，如果没有安装过就自动下载并安装插件再打开微信。

**Comment by YuyangHYY** [comment]
请问下`curl -o- -L https://raw.githubusercontent.com/lmk123/oh-my-wechat/master/install.sh | bash -s`运行完这个之后运行`omw`。以后我就不需要在进行[这个插件](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS)的安装了是吧，直接自动检测更新，自动安装配置是么？
还是说我这次运行完这两个命令之后，以后出现更新还要运行`omw`？

**Comment by lmk123** [comment]
运行完这两个命令后就不用管了，等哪天你发现微信小助手没了或微信小助手提示你有更新的时候，再运行一次 omw 就可以了
