### ISSUE TITLE
新版微信装完小助手,微信无限意外重启

### ISSUE THREAD

**Issue by yeziWee** [lmk123/oh-my-wechat#10]
早上更新了微信,然后重新安装小助手,微信就无限意外退出了

**Comment by yeziWee** [comment]
own n打开提示LSOpenURLsWithRole() failed with error -10810 for the file /Applications/WeChat.app.

**Comment by lmk123** [comment]
我这个项目仅仅是微信小助手的**安装/更新工具**，并不是微信小助手本身，微信小助手的问题请发到 [TKkk-iOSer/WeChatPlugin-MacOS](TKkk-iOSer/WeChatPlugin-MacOS)

**Comment by lmk123** [comment]
传送门：TKkk-iOSer/WeChatPlugin-MacOS#479
