### ISSUE TITLE
打开微信失败

### ISSUE THREAD

**Issue by BigCatGit** [lmk123/oh-my-wechat#103]
[11:24:04] 打开微信
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/WeChat.app.

**Comment by youdrew** [comment]
遇到了同样问题，在更新微信之后，微信小助手丢失，然后重新安装小助手，出现这个问题。

**Comment by BigCatGit** [comment]
当天重新安装了无数次不行，后来记不得哪天重启了下电脑，打开又好了

**Comment by myvipbackup2** [comment]
运行以下命令试试  

`codesign --sign - --force --deep /Applications/WeChat.app`

https://github.com/MustangYM/WeChatExtension-ForMac/issues/816#issuecomment-775024089

**Comment by lmk123** [comment]
看起来不是 Oh My Wechat 的问题，解决方案见楼上提供的链接
