### ISSUE TITLE
mac big sur 11.3系统会导致微信崩溃无法启动

### ISSUE THREAD

**Issue by cikichen** [lmk123/oh-my-wechat#108]
![image](https://user-images.githubusercontent.com/1478821/116237006-4a630800-a792-11eb-90b3-d6c95db6a381.png)

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
