### ISSUE TITLE
mac os 11.3 已无法拦截撤回消息

### ISSUE THREAD

**Issue by moyupoi** [lmk123/oh-my-wechat#109]
系统更新到11.3，2021.04.29的，对权限做了处理，已经无法对消息权限做拦截

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
