### ISSUE TITLE
安装成功了但是终端无法识别omw命令

### ISSUE THREAD

**Issue by WayneLyn** [lmk123/oh-my-wechat#111]
macOS 11.3.1
wechat 3.0.1

安装完后在终端使用omw
提示zsh: command not found: omw

**Comment by lmk123** [comment]
方便贴一下安装过程的截图吗？可能在安装过程中报错了但是没有提示安装失败

**Comment by WayneLyn** [comment]
不好意思，我后来发现了原因，主要是没有usr/local/bin这个文件夹导致omw命令没有，我后来装了个homebrew，再装omw就可以了

**Comment by lmk123** [comment]
看来跟 #17 是同一个问题。这个 bug 确实很久了，我有空了修一下 :joy:
