### ISSUE TITLE
被微信安全提醒了

### ISSUE THREAD

**Issue by 3642214** [lmk123/oh-my-wechat#116]
![E84C0428-5EAB-4B03-8AE8-D29343821A15](https://user-images.githubusercontent.com/7067644/125610807-a354436b-9542-4900-b392-0460b8ccaa31.jpeg)
刚收到的，有没人和我一样的，未使用其他插件，开了退群提醒和防撤回

**Comment by baranwang** [comment]
俺也一样

**Comment by konkona** [comment]
俺也一样

**Comment by fcoolish** [comment]
me too

**Comment by hzfvictory** [comment]
我也是  怎么避免啊

**Comment by justrustc** [comment]
+1

**Comment by danielgzd** [comment]
刚被提醒，擦，吓我一跳

**Comment by sunjianan9900** [comment]
只开免扫码登陆会被封吗

**Comment by 7fresh** [comment]
等一个结果

**Comment by never123450** [comment]
俺也一样

**Comment by cnwanyan** [comment]
+1

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
