### ISSUE TITLE
使用这个插件被微信警告了

### ISSUE THREAD

**Issue by chj-damon** [lmk123/oh-my-wechat#117]
强制我退出登录了

**Comment by chenyonghui100** [comment]
我也收到微信警告了

**Comment by johnhom1024** [comment]
我也遇到了😂

**Comment by dddrop** [comment]
我也遇到了

**Comment by ZenoTian** [comment]
+1

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
