### ISSUE TITLE
我在使用微信小助手的时候，出现了使用微信外挂，病情强制退出了我的微信；

### ISSUE THREAD

**Issue by supercating** [lmk123/oh-my-wechat#118]

**Comment by hectorqin** [comment]
+1
刚刚微信被封了

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
