### ISSUE TITLE
使用过检测僵尸粉功能后被微信检测到

### ISSUE THREAD

**Issue by andy2080** [lmk123/oh-my-wechat#119]
使用检测僵尸粉功能后被微信检测的，短暂封号，验证后解决，后续没有继续使用检测僵尸粉功能后还是被检测到使用外挂短暂封号，验证解决。

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
