### ISSUE TITLE
新版的微信最左边栏没有聊天、收藏、联系人、个人设置那几个tab了？

### ISSUE THREAD

**Issue by xiaos1** [lmk123/oh-my-wechat#121]
为什么新版的微信最左边栏没有聊天、收藏、联系人、个人设置那几个tab了？
通过双击聊天按钮可以自动定位到未读消息的，现在那个按钮没有了是bug还是我打开方式不对？
<img width="850" alt="image" src="https://user-images.githubusercontent.com/14722570/126447770-afbb1d06-a3b5-4dfa-be4b-1144abdc35d2.png">

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
