### ISSUE TITLE
“微信.app”因为出现问题而无法打开。

### ISSUE THREAD

**Issue by Rodinio** [lmk123/oh-my-wechat#122]
![image](https://user-images.githubusercontent.com/26924998/134928717-ebeb72b4-a549-4706-a6d5-052bd6ba6042.png)

请与开发者联系，以确定“微信.app”可以配合此macOS版本使用。您可能需要重新安装该应用程序。请务必安装适用于该应用程序和macOS的任何可用更新。

点按“报告”以查看更详细的信息，并将报告发送给Apple。

重启 卸载 安装都无法正常使用

**Comment by Rodinio** [comment]
当前为WeChat 3.2.0 版本 不能使用

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
