### ISSUE TITLE
安装后 电脑很卡

### ISSUE THREAD

**Issue by tingfeima** [lmk123/oh-my-wechat#123]

**Comment by lmk123** [comment]
我猜测这个是微信小助手的问题，我的工具仅仅只是把微信小助手安装到你的电脑了。

Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
