### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by lingbaeryi-strong** [lmk123/oh-my-wechat#124]
![image](https://user-images.githubusercontent.com/19935192/142577028-88b3bfcd-2340-46cc-b7f2-a9c604360a18.png)

**Comment by lmk123** [comment]
你的安装脚本有误。githubusercontent.com 已经被墙了，请使用 README 中的安装命令。

如果使用 README 中的安装命令还是有问题，欢迎继续留言。
