### ISSUE TITLE
我号被封了

### ISSUE THREAD

**Issue by Ox0400** [lmk123/oh-my-wechat#125]
8 号被封了一次, 解封后一切正常.

今天被封了一次, 朋友圈, 群组, 扫码登陆被禁用. 提示外挂程序.

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
