### ISSUE TITLE
It does not work after installation 

### ISSUE THREAD

**Issue by leoescn** [lmk123/oh-my-wechat#127]
I installed it but my Wechat does not change.

为了安装 Oh My WeChat，请输入密码 ：
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
sudo: 3 incorrect password attempts
开始下载 Oh My WeChat...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13354  100 13354    0     0  21957      0 --:--:-- --:--:-- --:--:-- 22145
ln: /usr/local/bin/omw: No such file or directory
成功安装 Oh My Wechat！即将安装微信小助手……
[13:01:47] 当前 Oh My WeChat 版本为 v2.1.4
[13:01:47] 当前微信小助手版本为 v3.4.1
[13:01:47] 已安装微信小助手且使用了 -n 参数，无需检查更新
[13:01:47] 未开启开机自动安装微信小助手
[13:01:47] 是否开启开机自动安装微信小助手, 以避免微信更新后卸载微信小助手？
1) 是
2) 否
你的选择：
[13:01:47] 打开微信

**Comment by lmk123** [comment]
从报错信息上看，你三次都输入了错误的密码。你需要正确输入你的登陆密码才行

**Comment by leoescn** [comment]
> 从报错信息上看，你三次都输入了错误的密码。你需要正确输入你的登陆密码才行

请问密码是什么？
