### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by leoescn** [lmk123/oh-my-wechat#128]
安装需要密码，密码是什么？

Last login: Sat Feb 25 13:00:38 on ttys000
leolong@Leos-Air ~ % curl -o- -L https://omw.limingkai.cn/install.sh | bash -s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   977  100   977    0     0   1982      0 --:--:-- --:--:-- --:--:--  2006
为了安装 Oh My WeChat，请输入密码 ：
Password:

**Comment by slowlyCode** [comment]
你自己的mac密码

**Comment by slowlyCode** [comment]
当前项目已经不维护了，可以换种安装方式

**Comment by lmk123** [comment]
> 你自己的mac密码

正解，也就是开机密码
