### ISSUE TITLE
添加卸载微信小助手的功能

### ISSUE THREAD

**Issue by lmk123** [lmk123/oh-my-wechat#13]
微信小助手出了一个问题 TKkk-iOSer/WeChatPlugin-MacOS#479 导致安装小助手之后微信打不开，owm 应该提供一个卸载微信小助手的功能，将微信还原到未安装小助手的状态，这样至少微信能正常打开。

**Comment by zhiweio** [comment]
卸载重装了微信发现可以正常打开了

```bash
卸载 Oh My WeChat
运行 curl -o- -L https://raw.githubusercontent.com/lmk123/oh-my-wechat/master/uninstall.sh | bash -s 即可。
```

**Comment by lmk123** [comment]
正常打开的原因是因为你重装了微信，不是因为你卸载了 omw

**Comment by zhiweio** [comment]
我意思是重装微信就好了，然后不要再运行 omw 了

**Comment by lmk123** [comment]
v1.0.0 版本已添加 `omw un` 命令用于卸载小助手和 Oh My WeChat 自身。
