### ISSUE TITLE
已提示成功安装，但无法在本机找到小助手

### ISSUE THREAD

**Issue by YeziGZ** [lmk123/oh-my-wechat#16]
Hi，你好！我采用了懒癌办法，在终端进行了安装，并提示「成功安装 oh-my-wechat，现在可以运行 omw 打开微信了」，但是在本机无法找到小助手，请问该如何处理？

**Comment by yangwenmai** [comment]
alfred 中，输入 `wx` 就会出现微信小助手。

另外，你登录上 WeChat 之后，在状态菜单栏最后也有微信小助手。

**Comment by YeziGZ** [comment]
@yangwenmai   在 alfred 中没有找到，微信重启登陆后在状态菜单栏也没有看到微信小助手哇

**Comment by yangwenmai** [comment]
你是用 `omw` 启动的吗？

**Comment by lmk123** [comment]
> 但是在本机无法找到小助手

安装 Oh My WeChat 之后，还需要运行 `omw` 安装小助手，我猜你是忘记了这一步

**Comment by lmk123** [comment]
这一步确实可能会容易漏掉，之后我在安装完 Oh My WeChat 之后就自动安装小助手吧

**Comment by lmk123** [comment]
我已经加上安装 Oh My WeChat 后自动安装微信小助手的功能了，你重新用懒癌方法安装一遍就可以了，如果还有问题可以继续留言

**Comment by YeziGZ** [comment]
是漏了这个步骤。
但是在安装小助手的过程中出现了新问题：我把 WeChatPlugin-MacOS-1.7.5.zip 安装包到下载文件夹，并在终端运行了 $ cd ~/Downloads && omw load 1.7.5 命令，终端提示 omw: command not found

**Comment by lmk123** [comment]
这说明你没有安装成功

**Comment by lmk123** [comment]
能提供一下你安装 Oh My WeChat 和运行 `omw load` 命令的截图吗？

**Comment by YeziGZ** [comment]
@lmk123  原来的安装运行提示成功了，但是运行小助手安装的时候显示无法查到该命令。不过你更新自动安装小助手的命令后，我重新试了一遍，安装成功了！这是截图 ：

![](https://ws4.sinaimg.cn/large/006tNc79gy1g1wkp02yi7j30u00zbti5.jpg)

**Comment by lmk123** [comment]
看到截图之后我明白了，其实 Oh My WeChat 没有安装到你的电脑上，只是安装之后把微信小助手给你安装上了 😂

这是一个 bug，我重新开一个 issue（#17），这个我先关了

**Comment by YeziGZ** [comment]
好的，谢谢。
