### ISSUE TITLE
无法登录新微信

### ISSUE THREAD

**Issue by licett** [lmk123/oh-my-wechat#18]
1. 小助手版本信息：
[15:10:08] 当前微信小助手版本为 v1.7.5
[15:10:08] 正在查询新版本……
[15:10:10] 微信小助手的最新版本为 v1.7.5
[15:10:10] 当前已经安装了最新版本的小助手，无需重新安装
[15:10:10] 打开微信
2. 系统与微信信息：
- 设备类型：iMac16,2
- 系统版本：版本 10.14.4（版号 18E226）
- 系统语言：zh-Hans
- 微信版本：[2019-03-26 15:44:24] v2.3.24.17 (12222) #08921c2f9
- 微信语言：zh-Hans
- 历史版本：[2019-03-05 18:40:41.046] Version. 2.3.23 (11915)  v2.3.23.17 (0x12031711) - #d1c666268
- 网络状态：Reachable via WiFi
- 显  示  器：*(1920x1080)/Retina
3. 问题描述：
- 通过微信小助手->登录新微信入口，点击无法登录新微信。Dock栏有类似应用启动，一闪而过，然后消失
4. 是否可复现：
- 必现

**Comment by lmk123** [comment]
我也重现了，但是  Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues) 去反馈。

P.S. 我看到有人跟你反馈同一个问题了 https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/517
