### ISSUE TITLE
能自定义微信的安装位置吗

### ISSUE THREAD

**Issue by zhenhappy** [lmk123/oh-my-wechat#2]
我微信的安装位置不在默认的/Applications, 我是放在我用户目录下的Applications

**Comment by lmk123** [comment]
我一会儿多加一个判断，如果 `/Applications` 下没有就去 `~/Applications` 查找微信

**Comment by lmk123** [comment]
改好了，你重新安装试试

ref: 500435a89b854949fcd2b09e7cb017f8101bf468
