### ISSUE TITLE
TKkk-iOSer/WeChatPlugin-MacOS库已经Removed了

### ISSUE THREAD

**Issue by iKuiki** [lmk123/oh-my-wechat#20]
不知以后还有啥办法可以装旧版不

**Comment by lmk123** [comment]
TKkk-iOSer/WeChatPlugin-MacOS 仓库 remove 了对 Oh My WeChat 没有影响，因为 Oh My WeChat 是从 [Releases](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/releases) 里下载安装包的，只要 Releases 里的文件还在，Oh My WeChat 就能正常使用。

这一点我在 README 里提一下。
