### ISSUE TITLE
小助手微信取消置底闪退

### ISSUE THREAD

**Issue by ChokW** [lmk123/oh-my-wechat#24]
环境: MacBook Pro MacOs 10.12.6
微信版本: Version. 2.3.25 (12482)
小助手版本 1.7.5

取消置底闪退

群组免打扰状态下置底后 点击取消置底会闪退 取消置底失败
公众号置底后 点击取消置底会闪退 取消置底失败

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues) 去反馈。
