### ISSUE TITLE
怎么卸载啊，omw un 并不能卸载

### ISSUE THREAD

**Issue by gee1k** [lmk123/oh-my-wechat#25]
怎么卸载啊，omw un 并不能卸载
![image](https://user-images.githubusercontent.com/12059800/60579484-c61de480-9db5-11e9-8e60-cb930c0c896b.png)

**Comment by dingdayu** [comment]
#27

**Comment by yangwenmai** [comment]
重新安装一下微信，不使用 omw 就恢复正常版本。

**Comment by lmk123** [comment]
这是因为你没有用最新版本的  Oh My WeChat，你需要先按照文档上的方法再安装一次 Oh My WeChat，然后才能用 `omw un`

如果你是想卸载 Oh My WeChat，那么运行 `rm /usr/local/bin/omw && rm -r ~/.oh_my_wechat` 就可以了。
