### ISSUE TITLE
什么时候更新最新版本啊

### ISSUE THREAD

**Issue by stevenliuit** [lmk123/oh-my-wechat#26]
什么时候更新2.3.26啊 好伤心 没更新了

**Comment by ppttvs** [comment]
已pull request

**Comment by lmk123** [comment]
@stevenliuit 已将小助手的下载源更新为 [MustangYM/WeChatExtension-ForMac](https://github.com/MustangYM/WeChatExtension-ForMac)

感谢 @ppttvs 的贡献
