### ISSUE TITLE
最新版本是1.9.6，建议更新下readme

### ISSUE THREAD

**Issue by kokdemo** [lmk123/oh-my-wechat#29]
此外，我之前用的版本是1.7.5 我发现这个版本已经不能输入 omw 自动升级了，必须要重新下载包安装一次。

**Comment by lmk123** [comment]
文档已更新。

> 不能输入 omw 自动升级了

有运行 `omw` 时候的截图吗？

**Comment by kokdemo** [comment]
没有了，1.7.5的时候输入 omw ，也是跑完全部流程，但是并没有实际的升级。

**Comment by lmk123** [comment]
下次贴上截图反馈给我吧，不然不知道错误出在哪里，这次我先关闭了
