### ISSUE TITLE
用户权限不足导致安装失败

### ISSUE THREAD

**Issue by XiangWei-Meng** [lmk123/oh-my-wechat#3]
curl: (23) Failed writing body (0 != 1917)
chmod: /usr/local/bin/omw: No such file or directory

**Comment by lmk123** [comment]
有重试过吗，可能是网络问题导致的，国内访问 GitHub 不太稳定

**Comment by 755966092** [comment]
一直都是这个问题   翻墙也不行的

**Comment by lmk123** [comment]
我试了一下是没有问题的，你们能提供一下你们的运行环境吗？macOS 版本、错误截图、所在地区等？

**Comment by 755966092** [comment]
![image](https://user-images.githubusercontent.com/22684309/41695046-e128f282-753f-11e8-804d-5f991dcdcb73.png)
![image](https://user-images.githubusercontent.com/22684309/41695078-03498f2a-7540-11e8-809a-0a88d84bb6b4.png)
在北京

**Comment by lmk123** [comment]
看完错误信息我知道了，你们是权限不足被拒绝了：

```
Warning: Failed to create the file /usr/local/bin/omw: Permission denied
```

@755966092 试试用下面这条命令安装（最前面加上了 `sudo`）:

```
sudo curl -o- -L https://raw.githubusercontent.com/lmk123/oh-my-wechat/master/install.sh | bash -s
```

**Comment by 755966092** [comment]
刚才我加了 也不行的
![image](https://user-images.githubusercontent.com/22684309/41695279-f6cf4112-7540-11e8-80ad-9aeb2ec79e77.png)

**Comment by lmk123** [comment]
运行 `ls -l /usr/local | grep bin` 看看是不是文件夹没有写权限，下面是我的：

![image](https://user-images.githubusercontent.com/5035625/41695527-f1b71ac8-7541-11e8-9bcf-68b430f04c44.png)

**Comment by 755966092** [comment]
![image](https://user-images.githubusercontent.com/22684309/41695589-326751e6-7542-11e8-901a-9b9874cc75f2.png)

**Comment by lmk123** [comment]
emmmmmm...当前用户是有写权限的，写入文件是不会被拒绝的。我刚才尝试了一下把我用户组的写权限去掉了，重新安装也是没问题的……

不过你还是试试把 “wheel” 用户组的写权限加上去之后再安装看看吧（死马当作活马医了 😂 

```
chmod g+w /usr/local/bin
```

**Comment by 755966092** [comment]
我下载了 zip包 安装上了

**Comment by lmk123** [comment]
突然想到还有一种可能，就是你当前登陆的用户并不是 root 也不在 wheel 组里面吧？运行 `id` 看看你是不是 root 或在 wheel 组里，下面是我的，省略了一部分：

```
id
uid=501(limingkai) gid=20(staff) groups=20(staff),12(everyone),80(admin)
```

可以看到我当前用户是 limingkai，并且我也在 admin 组里。如果你运行之后发现你的当前用户不是 root 而且你也不在 wheel 组里的话，你需要按照下面的步骤把自己加入到 wheel 这个组：

先运行 `whoami` 看看当前登陆的用户名是什么：

```
$ whoami
limingkai
```

然后将自己加入到 `wheel` 组：

```
$ usermod -a -G wheel limingkai
```

最后给 wheel 这个组加上写权限：

```
$ chmod g+w /usr/local/bin
```

**Comment by lmk123** [comment]
权限问题也是蛮麻烦的，我更新一下 README 吧 😂

**Comment by 755966092** [comment]
![image](https://user-images.githubusercontent.com/22684309/41696914-07439108-7549-11e8-8305-a9fafe354b7d.png)
s是这样的

**Comment by lmk123** [comment]
才发现 macOS 没有 `usermod` 命令 😂

试试这个：

```
$ sudo dseditgroup -o edit -a yz -t user wheel
```

来源：[How to add user to a group from Mac OS X command line?](https://superuser.com/questions/214004/how-to-add-user-to-a-group-from-mac-os-x-command-line)

**Comment by 755966092** [comment]
![image](https://user-images.githubusercontent.com/22684309/41699225-74609f04-7555-11e8-9556-ed309c08afbe.png)

**Comment by Zuckervent** [comment]
我也遇到了一毛一样的问题，请问如何解决呢==

**Comment by ByteRax** [comment]
+1

![image](https://user-images.githubusercontent.com/5227840/42125149-6f5e8db8-7ca3-11e8-9008-e052dfcc921f.png)

**Comment by lmk123** [comment]
hi 各位，我刚才尝试修复了这个问题，你们可以重新安装试试，我非常希望能得到你们的反馈！

**Comment by lmk123** [comment]
无反馈，默认已经修复了，如果还有问题可以继续添加回复
