### ISSUE TITLE
omw命令提示no such file or directory

### ISSUE THREAD

**Issue by a6822342** [lmk123/oh-my-wechat#30]
rt.

**Comment by lmk123** [comment]
提供一个截图给我吧，我不知道你是哪一步报了错

**Comment by a6822342** [comment]
> 提供一个截图给我吧，我不知道你是哪一步报了错

你好，我已经解决了，是我的目录下没有bin目录，自己建一个就可以了。

**Comment by lmk123** [comment]
那看来就是 #17，我一直没解决 😂

**Comment by kerraway** [comment]
> > 提供一个截图给我吧，我不知道你是哪一步报了错
> 
> 你好，我已经解决了，是我的目录下没有bin目录，自己建一个就可以了。

/usr/local/bin 目录吗？我这边有这个目录呀，一样报错，求助。
