### ISSUE TITLE
安装后重启微信，微信闪退

### ISSUE THREAD

**Issue by melodyWxy** [lmk123/oh-my-wechat#31]
rt

**Comment by lmk123** [comment]
oh my wechat 只是负责安装了[微信小助手](https://github.com/MustangYM/WeChatExtension-ForMac)，先判断一下你的问题是微信小助手本身的问题还是因为 oh my wechat 导致的，例如去[小助手的 issues](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 搜一下，或者通过其它安装方式安装小助手，看看还有没有问题。

我在微信小助手的 issues 搜到一些闪退的报告，不知道是否对你有帮助：https://github.com/MustangYM/WeChatExtension-ForMac/issues?utf8=%E2%9C%93&q=is%3Aissue+%E9%97%AA%E9%80%80

如果确定是 Oh My Wechat 的问题，你可以继续在这个问题下留言。
