### ISSUE TITLE
如何结合Alfred使用？

### ISSUE THREAD

**Issue by lebonnuit** [lmk123/oh-my-wechat#32]
在设置菜单看到alfred选项，在git没有找到相关说明qaq

**Comment by lmk123** [comment]
这个仓库是给微信小助手做的安装/更新工具，微信小助手本身的仓库在 https://github.com/MustangYM/WeChatExtension-ForMac

**Comment by lebonnuit** [comment]
谢谢！🙏


‑‑‑‑‑‑‑‑‑‑
Best regards，
DAI
