### ISSUE TITLE
更新了Version. 2.3.29 (12948)之后防撤回好像不生效了

### ISSUE THREAD

**Issue by xiangjunbo** [lmk123/oh-my-wechat#33]
重新安装omw也不可以 确认了选项打开了

**Comment by ID404** [comment]
我也遇到这个问题

**Comment by phpxcn** [comment]
我也遇到了

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues) 去反馈。
