### ISSUE TITLE
防撤回失效了

### ISSUE THREAD

**Issue by lifuyi** [lmk123/oh-my-wechat#37]
看不到回撤的消息了

**Comment by JasonLxj** [comment]
同样看不到了，微信版本2.3.29 (13326)微信小助手版本为 v1.7.5

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
