### ISSUE TITLE
能否兼容一下打开小程序？

### ISSUE THREAD

**Issue by justcodingnobb** [lmk123/oh-my-wechat#39]
目前beta版支持打开小程序，安装了小助手之后，打开小程序会弹出新的登录框而不是打开小程序，卸载恢复正常。

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
