### ISSUE TITLE
添加码云镜像

### ISSUE THREAD

**Issue by liesauer** [lmk123/oh-my-wechat#40]
其实把release的东西和仓库同步到码云，国内下载还是很香的，可避免国内用户下载的难题，默认github，用户可自由切换至gitee。

**Comment by liesauer** [comment]
closed due to no response.

**Comment by lmk123** [comment]
查了一下，发现码云已经有一个镜像了 https://gitee.com/mirrors/wechatextension-formac

我抽个空把下载和检测更新的逻辑改成码云的

**Comment by lmk123** [comment]
码云的镜像已经添加好了，现在默认就会从码云上检查更新 & 下载安装包，如果发现了 bug 欢迎提交 issue。
