### ISSUE TITLE
无法查询新版本

### ISSUE THREAD

**Issue by georgeyjm** [lmk123/oh-my-wechat#43]
<img width="646" alt="Screen Shot 2020-02-29 at 11 22 23" src="https://user-images.githubusercontent.com/7471824/75600055-d1ace100-5ae5-11ea-9a74-5975e98336f3.png">

**Comment by ghost** [comment]
估计是github改字段了，导致版本号没匹配到。
https://github.com/lmk123/oh-my-wechat/blob/fe9ac35e990c2dcb81ee31e951569d0878cbe601/main.sh#L158

`Location`改成`location`即可
```
latest_version=$(curl --retry 2 -I -s https://github.com/MustangYM/WeChatExtension-ForMac/releases/latest | grep location | sed -n 's/.*\/v\(.*\)/\1/p')
```

**Comment by ghost** [comment]
https://github.com/lmk123/oh-my-wechat/pull/42
这个解决方案更好，不过还没merge进来。
使用`grep`的`-i`参数忽略大小写。
```bash
latest_version=$(curl --retry 2 -I -s https://github.com/MustangYM/WeChatExtension-ForMac/releases/latest | grep -i Location | sed -n 's/.*\/v\(.*\)/\1/p')
```

**Comment by lmk123** [comment]
我刚才合并了 #42，现在应该没这个问题了
