### ISSUE TITLE
已提示成功安装，但是打开微信没有小助手

### ISSUE THREAD

**Issue by ghost** [lmk123/oh-my-wechat#45]
<img width="574" alt="截屏2020-03-0610 40 09" src="https://user-images.githubusercontent.com/61857181/76045057-0feb4a00-5f97-11ea-80ac-f6691f232235.png">
<img width="499" alt="截屏2020-03-0610 40 30" src="https://user-images.githubusercontent.com/61857181/76045068-14affe00-5f97-11ea-8053-85ba3b8cb7e5.png">

**Comment by lmk123** [comment]
卸载微信小助手然后再运行 `omw` 试试

**Comment by ghost** [comment]
> 卸载微信小助手然后再运行 `omw` 试试

已解决，谢谢！
