### ISSUE TITLE
经常提示查询更新失败

### ISSUE THREAD

**Issue by GengJian** [lmk123/oh-my-wechat#46]
实际上之前是安装过的，升级到2.4.0版本之后出现如下

➜  ~ omw
[11:54:58] 当前没有安装微信小助手
[11:54:58] 正在查询新版本……
[11:54:58] 查询新版本时失败，请稍后重试
➜  ~
![image](https://user-images.githubusercontent.com/13254245/76050155-69587680-5fa1-11ea-8eb1-14d0707a04fb.png)

**Comment by imtianx** [comment]
参照文档可使用 `omw -n`跳过检查更新,或者手动下载 [小助手](https://github.com/MustangYM/WeChatExtension-ForMac/releases)，用 `omw load version` 安装。

**Comment by lmk123** [comment]
原因是 GitHub 最近因为大家都知道的原因，网络不太稳定了，所以查询会频繁失败，可以参考楼上的方式用 `omw load` 安装

**Comment by lmk123** [comment]
后面我打算使用国内的镜像 https://gitee.com/mirrors/wechatextension-formac 来做检查更新和下载安装包的操作，进度会同步到 #40
