### ISSUE TITLE
安装失效

### ISSUE THREAD

**Issue by guoyida** [lmk123/oh-my-wechat#52]
[20:30:04] 下载完成
[20:30:04] 开始安装微信小助手……
/usr/local/bin/omw: line 249: ./WeChatExtension-ForMac-2.5.7/WeChatExtension/Rely/Install.sh: No such file or directory
[20:30:04] 微信小助手安装完成。
[20:30:04] 打开微信

**Comment by galenyuan** [comment]
+1

**Comment by lmk123** [comment]
此问题可能跟 #51 有关，请先运行 `omw un` 卸载 Oh My WeChat，然后按照 README.md 上提供的安装命令重新安装试试。

**Comment by galenyuan** [comment]
![image](https://user-images.githubusercontent.com/10335062/82628415-5c9e0300-9c1f-11ea-9f99-8fbba86af6c6.png)

@lmk123 亲测不行

**Comment by lmk123** [comment]
![image](https://user-images.githubusercontent.com/5035625/82628699-20b76d80-9c20-11ea-8c7e-ec1c44d92093.png)

目测是xx期间临时不让下载了。。

**Comment by galenyuan** [comment]
> ![image](https://user-images.githubusercontent.com/5035625/82628699-20b76d80-9c20-11ea-8c7e-ec1c44d92093.png)
> 
> 目测是xx期间临时不让下载了。。

哈哈哈，说关键字当心喝茶

**Comment by galenyuan** [comment]
亲测先通过 curl 安装后 `omw -g` 可解，但可能需要 terminal 代理一下，因为是直接从 Github 下载包的

**Comment by guoyida** [comment]
omw -g 搞定！
