### ISSUE TITLE
安装小助手失败

### ISSUE THREAD

**Issue by Chuck1sn** [lmk123/oh-my-wechat#53]
OS : mac 10.15.2
wechat:2.4.1

error msg
/usr/local/bin/omw: line 249: ./WeChatExtension-ForMac-2.5.7/WeChatExtension/Rely/Install.sh: No such file or directory

[16:06:22] 当前 Oh My WeChat 版本为 v1.3.2
[16:06:22] 当前没有安装微信小助手
[16:06:22] 未安装微信小助手，也没有下载过安装包，所以即使使用了 -n 参数，仍需要检查并下载新版本
[16:06:22] 正在查询新版本……
[16:06:36] 微信小助手的最新版本为 v2.5.7
[16:06:36] 开始下载微信小助手 v2.5.7……
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    64    0    64    0     0      5      0 --:--:--  0:00:10 --:--:--    13
[2.5.7.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of 2.5.7.zip or
        2.5.7.zip.zip, and cannot find 2.5.7.zip.ZIP, period.
mv: rename wechatextension-formac to WeChatExtension-ForMac-2.5.7: No such file or directory
[16:06:47] 下载完成
[16:06:47] 开始安装微信小助手……
/usr/local/bin/omw: line 249: ./WeChatExtension-ForMac-2.5.7/WeChatExtension/Rely/Install.sh: No such file or directory
[16:06:47] 微信小助手安装完成。
[16:06:47] 打开微信

打开微信后实际上并未成功安装小助手。

**Comment by p0we7** [comment]
如果有翻墙的话可以暂时先用以下命令更新 , 估计是国内源挂了。
```
omw -g
```

**Comment by Chuck1sn** [comment]
已使用 omw -g 安装成功
