### ISSUE TITLE
unzip:  cannot find zipfile directory in one of 2.5.8.zip or 2.5.8.zip.zip, and cannot find 2.5.8.zip.ZIP, period

### ISSUE THREAD

**Issue by MuYunyun** [lmk123/oh-my-wechat#54]
run `curl -o- -L https://omw.limingkai.cn/install.sh | bash -s`, then it print as follow:

![image](https://user-images.githubusercontent.com/19354791/83942887-4486d000-a82a-11ea-929a-baed64ae16d3.png)

**Comment by lmk123** [comment]
这是因为国内下载源近期关闭了，可以运行 `omw -g` 或者使用 `omw load` 命令安装小助手，文档中有说明
