### ISSUE TITLE
安装失败 有/user/local/bin目录

### ISSUE THREAD

**Issue by RWDai** [lmk123/oh-my-wechat#55]
![image](https://user-images.githubusercontent.com/27391645/84641757-18580700-af2e-11ea-8c8e-8e931cef28ce.png)

**Comment by lmk123** [comment]
这是因为国内下载源近期关闭了，可以运行 `omw -g` 或者使用 `omw load` 命令安装小助手，文档中有说明

**Comment by RWDai** [comment]
感谢
