### ISSUE TITLE
无法找到Install.sh文件

### ISSUE THREAD

**Issue by LeoBrighton** [lmk123/oh-my-wechat#56]
在运行curl -o- -L https://omw.limingkai.cn/install.sh | bash -s后，小助手做了两次尝试，第一次是因为bin文件夹不存在所以安装失败，第二次提示无法找到install.sh:
/Users/xxx/.oh_my_wechat/omw: line 249: ./WeChatExtension-ForMac-2.5.9/WeChatExtension/Rely/Install.sh: No such file or directory

**Comment by zhuziyi1989** [comment]
同样的问题复现在不同的系统里。

定位到 v2.6.0 这个版本确实有问题，之前版本无此问题。

➜  ~ omw
[11:37:52] 当前微信小助手版本为 v2.5.9
[11:37:52] 正在查询新版本……
[11:38:05] 微信小助手的最新版本为 v2.6.0
[11:38:05] 开始下载微信小助手 v2.6.0……
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    64    0    64    0     0      7      0 --:--:--  0:00:08 --:--:--    13
[2.6.0.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of 2.6.0.zip or
        2.6.0.zip.zip, and cannot find 2.6.0.zip.ZIP, period.
mv: rename wechatextension-formac to WeChatExtension-ForMac-2.6.0: No such file or directory
[11:38:14] 下载完成
[11:38:14] 开始安装微信小助手……
/usr/local/bin/omw: line 241: ./WeChatExtension-ForMac-2.6.0/WeChatExtension/Rely/Install.sh: No such file or directory
[11:38:14] 微信小助手安装完成。
[11:38:14] 检测到微信正在运行，请重启微信让小助手生效。

**Comment by Zhang-Siyang** [comment]
我也遇到了这个问题
```
$ curl -o- -L https://omw.limingkai.cn/install.sh | bash -s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   977  100   977    0     0    864      0  0:00:01  0:00:01 --:--:--   864
开始下载 Oh My WeChat...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11965  100 11965    0     0  42429      0 --:--:-- --:--:-- --:--:-- 42429
成功安装 Oh My Wechat！即将安装微信小助手……
[13:17:54] 当前 Oh My WeChat 版本为 v1.3.2
[13:17:54] 当前没有安装微信小助手
[13:17:54] 未安装微信小助手，也没有下载过安装包，所以即使使用了 -n 参数，仍需要检查并下载新版本
[13:17:54] 正在查询新版本……
[13:17:55] 微信小助手的最新版本为 v2.6.0
[13:17:55] 开始下载微信小助手 v2.6.0……
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    64    0    64    0     0    141      0 --:--:-- --:--:-- --:--:--   141
[2.6.0.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of 2.6.0.zip or
        2.6.0.zip.zip, and cannot find 2.6.0.zip.ZIP, period.
mv: rename wechatextension-formac to WeChatExtension-ForMac-2.6.0: No such file or directory
[13:17:56] 下载完成
[13:17:56] 开始安装微信小助手……
/Users/siyangz/.oh_my_wechat/omw: line 249: ./WeChatExtension-ForMac-2.6.0/WeChatExtension/Rely/Install.sh: No such file or directory
[13:17:56] 微信小助手安装完成。
[13:17:56] 检测到微信正在运行，请重启微信让小助手生效。
```

**Comment by lmk123** [comment]
实际上安装失败了，但是 omw 现在错误的显示了“下载完成”。

另外，出现这个问题的原因我也更新在文档里了：目前国内镜像仓库无法正常下载小助手，请使用 omw -g 或者 omw load 命令安装小助手。

**Comment by lmk123** [comment]
已在 v2.0.0 中去掉了国内下载源，大家可以运行 `omw update` 更新到 v2.0.0 版本
