### ISSUE TITLE
自动更新版本下载失败

### ISSUE THREAD

**Issue by DarinJi** [lmk123/oh-my-wechat#6]
一直下载失败

**Comment by lmk123** [comment]
运行截图贴一下我看看？

**Comment by DarinJi** [comment]
<img width="570" alt="wx20180808-145314 2x" src="https://user-images.githubusercontent.com/15549563/43822013-6c08dfc2-9b1d-11e8-9b2b-76b6e9d9e24a.png">

**Comment by lmk123** [comment]
出现这个提示一般是因为网络问题导致的，国内访问 GitHub 的下载地址确实不稳定，我这边能做的就是后期加一个代理的选项，让你能通过代理下载安装包。
