### ISSUE TITLE
在已经安装了微信小助手的状态下似乎无法安装Oh My WeChat？

### ISSUE THREAD

**Issue by XYZliang** [lmk123/oh-my-wechat#61]
![image](https://user-images.githubusercontent.com/59312540/89362988-b6cc4180-d701-11ea-8c3f-0aadc6738feb.png)
如图，当输入安装后，显示已经成功安装own，但是当我输入omw update时，却依然显示zsh: command not found: omw

系统macOS11.0
微信小助手 v2.6.3

**Comment by lmk123** [comment]
安装过程出错了，原因是你的系统里没有   /usr/local/bin 这个文件夹，这个 bug #17 我一直没有修复。你可以在 /usr/local 下自己建一个 bin 文件夹然后重新安装，参考 https://github.com/lmk123/oh-my-wechat/issues/30#issuecomment-526167346
