### ISSUE TITLE
拦截到崩溃

### ISSUE THREAD

**Issue by wl95** [lmk123/oh-my-wechat#62]
![image](https://user-images.githubusercontent.com/34021853/91162656-f5e92380-e6fe-11ea-86c8-b8f101a43557.png)
每次登陆都这样 需要多次点击确定

**Comment by wl95** [comment]
<img width="458" alt="3168186F-BAB2-44E0-A5BC-279F814DD868" src="https://user-images.githubusercontent.com/34021853/91163004-7445c580-e6ff-11ea-90a5-6a8d9cd174fb.png">

**Comment by wl95** [comment]
<img width="458" alt="3168186F-BAB2-44E0-A5BC-279F814DD868" src="https://user-images.githubusercontent.com/34021853/91163042-83c50e80-e6ff-11ea-87df-0b5009c80830.png">

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
