### ISSUE TITLE
安装小助手，似乎导致bartender不能隐藏图标

### ISSUE THREAD

**Issue by Creolophus** [lmk123/oh-my-wechat#63]
<img width="457" alt="截屏2020-09-02 下午5 31 38" src="https://user-images.githubusercontent.com/7787790/91964820-3883af00-ed42-11ea-8e59-84b28e0a59db.png">

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
