### ISSUE TITLE
big sur

### ISSUE THREAD

**Issue by lhd-1727865856** [lmk123/oh-my-wechat#69]
macOs big sur无法使用

**Comment by lmk123** [comment]
什么无法使用？是 Oh My WeChat 的命令行不能用还是微信小助手不能用？

**Comment by ghost** [comment]
我是big sur 正常使用 但是远程控制无反馈

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
