### ISSUE TITLE
安装插件后，微信转发图片闪退

### ISSUE THREAD

**Issue by bykgh** [lmk123/oh-my-wechat#71]
微信版本Version. 2.5.0 (15731)
系统版本 macOS Big Sur 11.1   和  macOS Catalina 10.15.6
微信小助手版本 V2.8.1
右键选择一张图片，选转发，就会闪退, 删除小助手后转发图片功能恢复正常

**Comment by lmk123** [comment]
这看起来是微信小助手的问题。

Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
