### ISSUE TITLE
安装后微信直接崩溃打不开

### ISSUE THREAD

**Issue by DreamNextHeart** [lmk123/oh-my-wechat#86]
微信版本：Version. 2.6.1 (16853)
微信小助手刚安装完毕就错误退出，后面一直打不开。

**Comment by yuanhao-chen-nyoeghau** [comment]
同样的问题，今天刚发现。

**Comment by lmk123** [comment]
Oh My WeChat 只是微信小助手的安装 / 更新工具，你这个问题是微信小助手自身的问题吧？

[无法启动bug MustangYM/WeChatExtension-ForMac ](https://github.com/MustangYM/WeChatExtension-ForMac/issues/816)
