### ISSUE TITLE
发送文件时微信会卡死

### ISSUE THREAD

**Issue by cenyk1230** [lmk123/oh-my-wechat#9]
mac os: 10.11.6
wechat version: Version. 2.3.21 (11699)
小助手版本: v1.7.3

在电脑端发送文件给别人时，会出现微信整个卡死的情况

**Comment by lmk123** [comment]
我这个项目仅仅是微信小助手的**安装/更新工具**，并不是微信小助手本身，微信小助手的问题请发到 [TKkk-iOSer/WeChatPlugin-MacOS](TKkk-iOSer/WeChatPlugin-MacOS)
