### ISSUE TITLE
安装后微信崩了

### ISSUE THREAD

**Issue by Z-fly** [lmk123/oh-my-wechat#92]
![image](https://user-images.githubusercontent.com/10470892/108298982-b7798080-71d8-11eb-8b7b-2c4d10348169.png)
![image](https://user-images.githubusercontent.com/10470892/108298907-ae88af00-71d8-11eb-8316-deadd1420869.png)

**Comment by Z-fly** [comment]
Process:               WeChat [2903]
Path:                  /Applications/WeChat.app/Contents/MacOS/WeChat
Identifier:            com.tencent.xinWeChat
Version:               2.6.1 (16871)
App Item ID:           836500024
App External ID:       840096642
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           WeChat [2903]
User ID:               501

Date/Time:             2021-02-18 11:02:33.353 +0800
OS Version:            Mac OS X 10.15.7 (19H512)
Report Version:        12
Anonymous UUID:        490707C9-8D11-2C06-7139-6CC8E18F19A1


Time Awake Since Boot: 9600 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension
  Referenced from: /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: no suitable image found.  Did find:
	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

Binary Images:
       0x10e858000 -        0x112c91fe7 +com.tencent.xinWeChat (2.6.1 - 16871) <39F8CEF5-8EB6-3F43-8288-1F4955EE2708> /Applications/WeChat.app/Contents/MacOS/WeChat
       0x1142e4000 -        0x114424fff +com.tencent.WCDB (1.0.3 - 1) <70A1B57B-7EB5-3E13-91D7-E6927266EEE0> /Applications/WeChat.app/Contents/Frameworks/WCDB.framework/Versions/A/WCDB
       0x1144bd000 -        0x1144c2ff7 +com.tencent.MMLibHooks (1.0 - 1) <5901B561-6343-33D6-924A-43368BBD16F5> /Applications/WeChat.app/Contents/Frameworks/MMLibHooks.framework/Versions/A/MMLibHooks
       0x1144cf000 -        0x1144f1ff7 +com.deusty.CocoaLumberjack (2.3.0 - 1) <6BDB40E8-05DA-32DE-8C81-37632C48E80B> /Applications/WeChat.app/Contents/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack
       0x114527000 -        0x114549ffb +com.alamofire.AFNetworking (3.0.0 - 3.1.0) <BDD10371-3F15-3EF9-A0A7-E80EAC53ADF6> /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking
       0x11458c000 -        0x11462cfff +tencent.matrixreport (1.0 - 1) <2586BD60-1797-3862-B461-CA38A7E71FAA> /Applications/WeChat.app/Contents/Frameworks/matrixreport.framework/Versions/A/matrixreport
       0x11f6d9000 -        0x11f76af47  dyld (750.6) <326C6480-04F4-3164-A363-53079A148E2F> /usr/lib/dyld
    0x7fff2e272000 -     0x7fff2e46dff8  com.apple.avfoundation (2.0 - 1855.3) <0837D912-3783-35D6-A94A-E474E18600CF> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff2e53c000 -     0x7fff2e659ff6  com.apple.AVKit (1.1 - 600.2) <41B403F1-2F32-37BB-A0D7-B84AF3F1734B> /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
    0x7fff2e65a000 -     0x7fff2e65afff  com.apple.Accelerate (1.11 - Accelerate 1.11) <4F9977AE-DBDB-3A16-A536-AC1F9938DCDD> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff2fc86000 -     0x7fff30a46ff2  com.apple.AppKit (6.9 - 1894.60.100) <035927A5-657C-3D54-B9AA-0BBE7307514E> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff30dc8000 -     0x7fff30ea9ffa  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <5B249BE8-90C2-303D-9D08-7E829341DB23> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff30eab000 -     0x7fff30eabfff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <19BFF349-A9A2-355A-96F9-3ACD50231B0D> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff31242000 -     0x7fff315d1ffa  com.apple.CFNetwork (1128.0.2 - 1128.0.2) <967D1958-9BAD-3582-B63D-C4088D43D69B> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff3164d000 -     0x7fff3164dfff  com.apple.Carbon (160 - 162) <93F221F5-B31E-31F4-ACC7-7840171C61E3> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff31b31000 -     0x7fff31b31fff  com.apple.Cocoa (6.11 - 23) <94D1D6CE-8EFB-3EBF-A662-29F5AA6F963D> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff31f20000 -     0x7fff32429ffb  com.apple.audio.CoreAudio (5.0 - 5.0) <47923B12-3D14-328A-9C86-27A3A2A73068> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff329d3000 -     0x7fff32e52feb  com.apple.CoreFoundation (6.9 - 1677.201) <56B0FE5F-D493-3DF1-ABFF-ECC450268B97> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff32e54000 -     0x7fff334c9ff8  com.apple.CoreGraphics (2.0 - 1355.22) <438C1588-4EA6-3648-9905-53E804DC179A> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff33833000 -     0x7fff3389cff0  com.apple.corelocation (2394.0.22 - 2394.0.22) <75966124-2FB7-33C3-BE49-3DD5F327F911> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff33bf3000 -     0x7fff33cceffc  com.apple.CoreMedia (1.0 - 2625.9) <A3FF3AFC-8C1C-36E5-9179-66D8F075EE35> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff33dbb000 -     0x7fff33dbbfff  com.apple.CoreServices (1069.24 - 1069.24) <4DCFF933-1368-322A-97AB-C3BBEF8E5BBE> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff3482e000 -     0x7fff349e5ffc  com.apple.CoreText (643.1.5.4 - 643.1.5.4) <9962BA1D-8858-36FC-9C1E-856F59CB73C8> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff349e6000 -     0x7fff34a2affb  com.apple.CoreVideo (1.8 - 344.3) <5314E70D-325F-3E98-99FC-00FDF520747E> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff34a2b000 -     0x7fff34ab8ffc  com.apple.framework.CoreWLAN (13.0 - 1601.2) <6223BFD5-D451-3DE9-90F6-F609AC0B0027> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff35090000 -     0x7fff35455fff  com.apple.Foundation (6.9 - 1677.201) <E020DC09-4221-3961-A450-638525789B38> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff357c9000 -     0x7fff3586dff3  com.apple.framework.IOKit (2.0.2 - 1726.148.1) <0A9D244C-AECC-3D29-86DE-4F3B04F8DD25> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff358ff000 -     0x7fff35a5cfe6  com.apple.ImageIO.framework (3.3.0 - 1976.11.4) <B6BE5D70-F74D-3436-BED7-E5F0BB104F74> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff362c9000 -     0x7fff37369ff1  com.apple.JavaScriptCore (15609 - 15609.4.1) <18766B97-AB12-331C-984C-F1C7C9363E8B> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff39301000 -     0x7fff3934bff8  com.apple.MultipeerConnectivity (166 - 166) <ECB78B83-E384-3079-915E-2D7C791DCD2E> /System/Library/Frameworks/MultipeerConnectivity.framework/Versions/A/MultipeerConnectivity
    0x7fff397d6000 -     0x7fff397f8fff  com.apple.audio.OpenAL (1.8 - 1.8) <6D66C5D7-8410-35B7-B06E-3BE56E0A708E> /System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL
    0x7fff3d567000 -     0x7fff3d576ff7  com.apple.opengl (17.10.22 - 17.10.22) <4D43EB22-BD57-3493-B574-332E13657FE9> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff3e533000 -     0x7fff3e533fff  com.apple.quartzframework (1.5 - 23) <112CB670-9241-3CE1-B857-B81DF2623BBC> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff3e534000 -     0x7fff3e7b7ffb  com.apple.QuartzCore (1.11 - 841.4) <0028ADD7-42AD-310E-B725-2DF94C07FD6D> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff3e7b8000 -     0x7fff3e811ff5  com.apple.QuickLookFramework (5.0 - 906.3) <959CE934-B541-3172-846F-4D1709353526> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff3f33a000 -     0x7fff3f683ff1  com.apple.security (7.0 - 59306.140.5) <B6F8368F-2395-379B-B768-71C53BB1B903> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff3f73b000 -     0x7fff3f73fff8  com.apple.xpc.ServiceManagement (1.0 - 1) <9B36FD0E-D280-35EB-ABAB-6AC5D7B2118F> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff403eb000 -     0x7fff40465ff7  com.apple.SystemConfiguration (1.19 - 1.19) <84F9B3BB-F7AF-3B7C-8CD0-D3C22D19619F> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff406e5000 -     0x7fff40a68ff4  com.apple.VideoToolbox (1.0 - 2625.9) <6CF18E28-A7A8-3952-8171-7E4FF4FB37FA> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff43920000 -     0x7fff44025ffd  com.apple.WebKit (15609 - 15609.4.1) <B514329D-F257-310E-B562-C23C20920075> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff69adb000 -     0x7fff69adcfff  libSystem.B.dylib (1281.100.1) <C49167AD-722B-3DF3-9031-7D6B59FC2A06> /usr/lib/libSystem.B.dylib
    0x7fff69db4000 -     0x7fff69dc0fff  libbz2.1.0.dylib (44) <14CC4988-B6D4-3879-AFC2-9A0DDC6388DE> /usr/lib/libbz2.1.0.dylib
    0x7fff69dc1000 -     0x7fff69e13fff  libc++.1.dylib (902.1) <59A8239F-C28A-3B59-B8FA-11340DC85EDC> /usr/lib/libc++.1.dylib
    0x7fff6a8b4000 -     0x7fff6a9a4fff  libiconv.2.dylib (59) <18311A67-E4EF-3CC7-95B3-C0EDEE3A282F> /usr/lib/libiconv.2.dylib
    0x7fff6a9a5000 -     0x7fff6abfcfff  libicucore.A.dylib (64260.0.1) <8AC2CB07-E7E0-340D-A849-186FA1F27251> /usr/lib/libicucore.A.dylib
    0x7fff6b93b000 -     0x7fff6b96efde  libobjc.A.dylib (787.1) <6DF81160-5E7F-3E31-AA1E-C875E3B98AF6> /usr/lib/libobjc.A.dylib
    0x7fff6ba42000 -     0x7fff6ba5afff  libresolv.9.dylib (67.40.1) <C57EDFEF-D36A-310B-8D14-8C68A625B1E8> /usr/lib/libresolv.9.dylib
    0x7fff6bf08000 -     0x7fff6bfeafff  libxml2.2.dylib (33.8) <FE38B007-24AF-310D-B834-2C9466154CEC> /usr/lib/libxml2.2.dylib
    0x7fff6c017000 -     0x7fff6c029ff3  libz.1.dylib (76) <793D9643-CD83-3AAC-8B96-88D548FAB620> /usr/lib/libz.1.dylib
    0x7fff6c0e0000 -     0x7fff6c0f672f  libswiftAppKit.dylib (??? - ???) <18802260-9EFC-3E31-B9EA-7767A8B6AB52> /usr/lib/swift/libswiftAppKit.dylib
    0x7fff6c120000 -     0x7fff6c4d5437  libswiftCore.dylib (5.2 - 1103.8.25.8) <E56CCFCA-99E1-36E5-A6BC-F31F53C79910> /usr/lib/swift/libswiftCore.dylib
    0x7fff6c4e2000 -     0x7fff6c4ead7f  libswiftCoreData.dylib (??? - ???) <5188E034-FC7D-3C6B-A42A-69375097E05B> /usr/lib/swift/libswiftCoreData.dylib
    0x7fff6c4eb000 -     0x7fff6c4edfff  libswiftCoreFoundation.dylib (??? - ???) <FBA4566B-AD2B-35D7-BC9A-48BE3D88B658> /usr/lib/swift/libswiftCoreFoundation.dylib
    0x7fff6c4ee000 -     0x7fff6c4fbfff  libswiftCoreGraphics.dylib (??? - ???) <A8225B5F-F64D-32F8-AD91-D919DF614AA0> /usr/lib/swift/libswiftCoreGraphics.dylib
    0x7fff6c4fc000 -     0x7fff6c4ffffb  libswiftCoreImage.dylib (??? - ???) <1485E8EF-EDA9-3981-84D7-DF3BFE361929> /usr/lib/swift/libswiftCoreImage.dylib
    0x7fff6c55a000 -     0x7fff6c560fff  libswiftDarwin.dylib (??? - ???) <F3684684-8258-310F-B05B-BD8A696F0F29> /usr/lib/swift/libswiftDarwin.dylib
    0x7fff6c561000 -     0x7fff6c578cdf  libswiftDispatch.dylib (??? - ???) <94D67EF4-42B5-3F54-8D86-B6B2B16827DC> /usr/lib/swift/libswiftDispatch.dylib
    0x7fff6c579000 -     0x7fff6c6fe277  libswiftFoundation.dylib (??? - ???) <0173898D-FDA6-378D-87E9-1F2A9BD227D3> /usr/lib/swift/libswiftFoundation.dylib
    0x7fff6c70d000 -     0x7fff6c70fff3  libswiftIOKit.dylib (??? - ???) <FD313708-AE48-3C72-A154-53EC839A8D55> /usr/lib/swift/libswiftIOKit.dylib
    0x7fff6c725000 -     0x7fff6c72cf0f  libswiftMetal.dylib (??? - ???) <B3C74138-DE3C-3676-9983-F12757819C9C> /usr/lib/swift/libswiftMetal.dylib
    0x7fff6c7a8000 -     0x7fff6c7abfe7  libswiftObjectiveC.dylib (??? - ???) <E668BD5D-E1D6-3C21-BA7E-5C3A672A964E> /usr/lib/swift/libswiftObjectiveC.dylib
    0x7fff6c7bd000 -     0x7fff6c7c2fbf  libswiftQuartzCore.dylib (??? - ???) <101D3E4D-231A-3CD8-97B4-4E37F4081CD2> /usr/lib/swift/libswiftQuartzCore.dylib
    0x7fff6c8ac000 -     0x7fff6c8aefff  libswiftXPC.dylib (??? - ???) <3CD547C3-7082-37EA-B289-F6BA6C4D4E26> /usr/lib/swift/libswiftXPC.dylib

**Comment by wangzi0218** [comment]
同遇到这个问题，已有的微信+插件在新打开的时候提示崩溃

**Comment by Master-cai** [comment]
同样遇到了这个问题，macOS版本为10.15.4

**Comment by Z-fly** [comment]
> 同遇到这个问题，已有的微信+插件在新打开的时候提示崩溃

解决了，安装最新版本插件就行

**Comment by Z-fly** [comment]
> 同样遇到了这个问题，macOS版本为10.15.4

解决了，安装最新版本插件就行

**Comment by ChaosTong** [comment]
需要手动将微信小助手更新到2.8.3, 检测更新那里出现了问题不能检测到2.8.3导致无法自动更新, 2.8.3版本修复了闪退的问题 @wangzi0218 @Master-cai , 因为这次用了大写字母V, 有人已经提交了 pull request, 还没合并

**Comment by lmk123** [comment]
这是微信小助手自身的问题，最新版本微信小助手已经解决了。

**Comment by Z-fly** [comment]
> 这是微信小助手自身的问题，最新版本微信小助手已经解决了。
oh-my-wechat 什么时候同步更新呢？
