### ISSUE TITLE
新版本使用 omw 更新 会报错，并且微信会闪退

### ISSUE THREAD

**Issue by BillScott1024** [lmk123/oh-my-wechat#93]
![image](https://user-images.githubusercontent.com/22955480/108456119-88334400-72aa-11eb-8500-94a98048ed28.png)

**Comment by BillScott1024** [comment]
![image](https://user-images.githubusercontent.com/22955480/108456176-b4e75b80-72aa-11eb-8877-916f5f4535ce.png)

**Comment by BillScott1024** [comment]
![image](https://user-images.githubusercontent.com/22955480/108456208-cc264900-72aa-11eb-8399-41176285e66a.png)

**Comment by lmk123** [comment]
`End-of-central-directory` 这个错误一般是由于网络不稳定导致文件没下载完整就中断了，你可以：

- 过会儿再试试
- 挂上梯子试试
- 实在不行，你可以自行下载 v2.8.3 的安装包用 `omw load` 导入

微信闪退是[微信小助手 v2.8.2 的问题](https://github.com/MustangYM/WeChatExtension-ForMac/issues/816)，更新到 v2.8.3 就没有这个问题了。

**Comment by liziqiang** [comment]
小助手那边最新版本是V2.8.3，get_download_url这个方法下载的地址是v2.8.3，是不是这个原因导致的 @lmk123

**Comment by lmk123** [comment]
> 小助手那边最新版本是V2.8.3，get_download_url这个方法下载的地址是v2.8.3，是不是这个原因导致的

是的，确实是这个原因导致的。我会尽快修复这个问题

**Comment by liziqiang** [comment]
> > 小助手那边最新版本是V2.8.3，get_download_url这个方法下载的地址是v2.8.3，是不是这个原因导致的
> 
> 是的，确实是这个原因导致的。我会尽快修复这个问题

提了个PR，有时间看一下哈~ https://github.com/lmk123/oh-my-wechat/pull/98

**Comment by lmk123** [comment]
我发现微信小助手把版本号改回来成小写 v 开头的了，所以现在应该是没这个问题了。

@liziqiang 感谢 PR，我也在 PR 里给你回复了。
