### ISSUE TITLE
omw在新版微信中不生效

### ISSUE THREAD

**Issue by Aaron-QL** [lmk123/oh-my-wechat#95]
当前 Oh My WeChat 版本为 v2.1.3
当前微信小助手版本为 v2.8.3

通过omw命令能启动微信，但打开后菜单栏中看不到助手那一列，且界面样式没生效

**Comment by dourgulf** [comment]
+10086

**Comment by dourgulf** [comment]
直接clone插件下来执行安装程序就好了

**Comment by lmk123** [comment]
将 omw 升级到 v2.1.4 之后重新运行 omw 安装一次小助手就可以了。
