### ISSUE TITLE
新版本无法使用ohmywechat

### ISSUE THREAD

**Issue by lnsslimbo** [lmk123/oh-my-wechat#96]
没装小助手之前可以打开，装了以后就无法打开了

**Comment by fhefh2015** [comment]
无法启动bug · Issue #816 · MustangYM/WeChatExtension-ForMac 
https://github.com/MustangYM/WeChatExtension-ForMac/issues/816

**Comment by lmk123** [comment]
这是微信小助手的问题，不是 Oh My WeChat 的问题。

Oh My WeChat 只是微信小助手的安装 / 更新工具，微信小助手自身的问题请到[它自己的 issue](https://github.com/MustangYM/WeChatExtension-ForMac/issues) 去反馈。
