### ISSUE TITLE
用懒癌或者下载zip安装后打开微信就出现报错不能打开微信 怎么解决啊

### ISSUE THREAD

**Issue by 15145072127** [lmk123/oh-my-wechat#97]
![8F52E460-B6C3-4CA6-8E56-0A194F55612C](https://user-images.githubusercontent.com/49505884/108796950-f5094f80-75c4-11eb-9b58-d237a9b4db05.png)

**Comment by fhefh2015** [comment]
无法启动bug · Issue #816 · MustangYM/WeChatExtension-ForMac 
https://github.com/MustangYM/WeChatExtension-ForMac/issues/816 
试一试 看看行吗~

**Comment by lmk123** [comment]
这是微信小助手的问题，不是 Oh My Wechat 的问题，所以先关闭了。
