### ISSUE TITLE
报错 bad flag in substitute command: 'i'

### ISSUE THREAD

**Issue by JesseWeb** [lmk123/oh-my-wechat#99]
应该是这个导致的 's/.*\/v\(.*\)/\1/ip'

**Comment by misakichan** [comment]
同样的问题 sed: 1: "s/.*\/v\(.*\)/\1/ip": bad flag in substitute command: 'i'

**Comment by JesseWeb** [comment]
#100
上面pr修复了这个问题，等待合并。
i already made this pr. plz check that out.

**Comment by lmk123** [comment]
将 omw 升级到 v2.1.4 即可解决这个问题。

**Comment by JesseWeb** [comment]
take look #104 for this case
